### ISSUE TITLE
怎么设置导航栏颜色？

### ISSUE THREAD

**Issue by acomet** [TP-Lab/tp-js-sdk#10]
绝大多数dapp导航栏是白色的， 但也有黑色、蓝色，那么是通过哪个api来更换导航栏颜色的呢 ？

**Comment by chendatony31** [comment]
只有上架TP的dapp 可以 找我们运营 来配置，不支持 开发者 自己设置 @acomet

**Comment by acomet** [comment]
> 只有上架TP的dapp 可以 找我们运营 来配置，不支持 开发者 自己设置 @acomet

好的 ，谢谢。
