### ISSUE TITLE
如何判断是观察钱包

### ISSUE THREAD

**Issue by Lloyd1229** [TP-Lab/tp-js-sdk#11]
根据哪个方法里的哪个字段可以判断出是观察钱包地址，而不是我导入私钥或者主记词的地址

**Comment by chendatony31** [comment]
getCurrentWallet  返回值里 有个 walletType ， 能区分是 observeWallet 还是 normalWallet

**Comment by Lloyd1229** [comment]
> getCurrentWallet 返回值里 有个 walletType ， 能区分是 observeWallet 还是 normalWallet

自己试到了，还是感谢
