### ISSUE TITLE
不完全明白?:已经支持了Scatter, MetaMask, TronLink, iWallet插件的Dapp可以直接在钱包内使用Dapp浏览器体验，无需再使用我们这个SDK

### ISSUE THREAD

**Issue by dlgchg** [TP-Lab/tp-js-sdk#12]
我能否直接像pc中使用,比如: window.ethereum.request({ method: "eth_requestAccounts" }); 这个可以调起chrome中metamask插件,但是我用tp就不行

**Comment by chendatony31** [comment]
可以的，只是tp 不会弹框 直接返回当前 钱包

**Comment by dlgchg** [comment]
明白了, 谢谢
