### ISSUE TITLE
为什么dapp的window.ethereum在安卓版钱包获取不到

### ISSUE THREAD

**Issue by alwkzo** [TP-Lab/tp-js-sdk#13]
安卓版本的TP钱包，有时候打开正常，切换页面又获取不到 window.ethereum，然后有时刷新又正常，然后切换来切换去又不行了。

ios版本的钱包不存在这个问题，我看其它imtoken钱包都不会出现这样问题，请问需要怎么解决？

**Comment by chendatony31** [comment]
尝试 在页面加载完后 再去 获取 window.ethereum 可能有延迟

**Comment by alwkzo** [comment]
@chendatony31 改成加载完在执行就可以了，在请教一个问题，就是 MetaMask 里面的监听在TP里面需要怎么操作，好像没反应。

        // 监听事件，账户变化时触发
        window.ethereum.on('accountsChanged', function(accounts) {
            window.location.reload();
        });
        // 监听事件，网络变化时触发
        window.ethereum.on('networkChanged', function(result) {
            window.location.reload();
        });

**Comment by alwkzo** [comment]
测了下，这部分安卓正常，ios上不行，有刷新的进度条在执行，页面内容实际没刷新

**Comment by chendatony31** [comment]
什么情况下 导致的 accountsChanged 或 networkChanged tp里确实没有 这个事件 手动去reload 一下？

**Comment by alwkzo** [comment]
@chendatony31 一般就是切换账号的时候触发

**Comment by chendatony31** [comment]
在TP钱包里 么？ 理论上 应该会刷新页面的哦

**Comment by alwkzo** [comment]
@chendatony31 是的在TP钱包，安卓版本正常，在ios苹果版本的TP钱包不行。页面好像有进度条闪了一下，可是页面内容没刷新的变化

**Comment by chendatony31** [comment]
加我github 账号这个微信吧 录个屏看下 @alwkzo
