### ISSUE TITLE
H5页面在安卓版TP钱包调用扫码功能受限的问题。

### ISSUE THREAD

**Issue by 382303784** [TP-Lab/tp-js-sdk#14]
![1634707200(1)](https://user-images.githubusercontent.com/38471024/138032642-ac0de9a6-fec3-4376-beba-fcd1bf8dfb48.png)
嗨，我确认打开了权限，但是调用扫码功能时  仍然遇到了这个问题？我该如何解决。谢谢。目前测试华为和小米都遇到了这个问题。

**Comment by NullPointerDuke** [comment]
> ![1634707200(1)](https://user-images.githubusercontent.com/38471024/138032642-ac0de9a6-fec3-4376-beba-fcd1bf8dfb48.png) 嗨，我确认打开了权限，但是调用扫码功能时 仍然遇到了这个问题？我该如何解决。谢谢。目前测试华为和小米都遇到了这个问题。

提供下详细的手机型号和Android系统版本号
