### ISSUE TITLE
ios版TP钱包内dapp无法调起网络切换功能getWallet

### ISSUE THREAD

**Issue by econiche** [TP-Lab/tp-js-sdk#15]
`tp.getWallet({ switch: true }).then(res => {
                alert(res.data[0].blockchain)
}`

**Comment by chendatony31** [comment]
`tp.getWallet({ switch: true, walletTypes: ['eth'] }).then(res => { alert(res.data[0].blockchain) }` try to add `walletTypes`

**Comment by econiche** [comment]
`walletTypes`  
It can run after adding this parameter.  
But because of the addition of this parameter, you can only see several networks pre-configured, I can't switch to custom networks.
What should I do?

**Comment by chendatony31** [comment]
If the custom network is an EVM compatible chain using `wallet_switchEthereumChain` instead: https://docs.metamask.io/guide/rpc-api.html#usage-with-wallet-switchethereumchain

**Comment by econiche** [comment]
> 

Get it! Thanks.
