### ISSUE TITLE
移动端 dapp 浏览器 window.ethereum 未定义

### ISSUE THREAD

**Issue by crapthings** [TP-Lab/tp-js-sdk#18]
貌似桌面端安装扩展以后是兼容的，移动端未定义

测试过 load 和 domcontentloaded 事件，设了一个延迟发现没有 window.ethereum 哦

**Comment by chendatony31** [comment]
确认下当前钱包是  evm 底层的公链 才有这个对象 @crapthings

**Comment by crapthings** [comment]
@chendatony31 bsc　的测试网络

我创建了一个新的项目用最简单的环境试验是好使的，但是不知道为啥接手的这个项目不行

**Comment by crapthings** [comment]
@chendatony31 已经确认是 iframe　的问题，现在程序都进去了

不过合约的方法拉起支付界面好像没有效果？桌面浏览器配合钱包扩展插件是好使的？浏览器怎么看ｃｏｎｓｏｌｅ呢？

**Comment by chendatony31** [comment]
@crapthings   可以自己引入一个 vconsole 库

**Comment by crapthings** [comment]
@chendatony31 

确认还是 iframe 问题，就好了。感谢 @chendatony31 

window.ethereum || window.parent.ethereum

**Comment by yuan520521** [comment]
我也有同样的问题，首次进入没有这个对象，刷新下页面就有了，搞不懂为什么
