### ISSUE TITLE
tp钱包中嵌套的h5如何上传图片

### ISSUE THREAD

**Issue by boonook** [TP-Lab/tp-js-sdk#19]
tp钱包中嵌套的h5使用formdata无法上传图片，图片文件在tp钱包中也无法转化成base64

**Comment by boonook** [comment]
图片是用来做公告新闻的封面图片使用的

**Comment by boonook** [comment]
tp钱包中上传图片ios没有问题，目前问题只出现在android上

**Comment by NullPointerDuke** [comment]
Android系统版本号和手机型号发下

**Comment by boonook** [comment]
华为mate40pro  
![76b837d993cd35e3f5f02887b3372b2](https://user-images.githubusercontent.com/34494413/148896045-020a54cc-3b3d-413b-b19c-7fdfcb55d606.jpg)

**Comment by boonook** [comment]
> Android系统版本号和手机型号发下

发给你了你查看一下

**Comment by NullPointerDuke** [comment]
你是上传报错还是选择图片报错？

**Comment by boonook** [comment]
上传的时候报错，选择图片都没有问题

**Comment by boonook** [comment]
![110c7a69b192f6f6881e9c3cfb04c34](https://user-images.githubusercontent.com/34494413/148896327-2750c0c5-173d-472d-ad03-225f9502de94.jpg)
```js
           let file = e.target.files[0];
            console.log('图片--1--',file);
            console.log('图片--1type--',state.suffix);
            let reader = new FileReader();
            reader.readAsDataURL(file)
            reader.onload = () => {
                state.file = reader.result;
                console.log('图片--2--',state.file);
            }
            reader.onerror = function (error) {
                console.log('Error: ', error)
            }
```
没有走onload直接走的onerror，

**Comment by boonook** [comment]
![d4080725c340dab59b8b88ba6830f78](https://user-images.githubusercontent.com/34494413/148896857-468dff72-3aaf-43b8-952b-29f98bcb0d2c.jpg)
这个是使用formdata返回的结果

**Comment by boonook** [comment]
> 你是上传报错还是选择图片报错？

报错消息我发出来了您可以查看一下对您有没有帮助

**Comment by boonook** [comment]
> 华为mate40pro ![76b837d993cd35e3f5f02887b3372b2](https://user-images.githubusercontent.com/34494413/148896045-020a54cc-3b3d-413b-b19c-7fdfcb55d606.jpg)

**Comment by boonook** [comment]
> 你是上传报错还是选择图片报错？

 <input type="file" placeholder="选择图片" accept="image/*" id="uploadimg" name="uploadimg" @change="onChange($event)">

**Comment by boonook** [comment]
> 你是上传报错还是选择图片报错？

大佬求教一下你们复现出问题了吗？

**Comment by NullPointerDuke** [comment]
这个问题新版本已经修复。

**Comment by NullPointerDuke** [comment]
1.3.9
