### ISSUE TITLE
tokenpocket里的dapp调用交易详细层是tokenpocket的，还是自己设计的页面层？

### ISSUE THREAD

**Issue by wuyongzhi1985** [TP-Lab/tp-js-sdk#23]
![c3f6033079b1e05028732a12c1ae051](https://user-images.githubusercontent.com/9312724/154954218-f91d8563-ec3b-46ef-a610-650fa94c8cb3.jpg)

**Comment by chendatony31** [comment]
tp 自己的 不需要额外设计 @wuyongzhi1985
