### ISSUE TITLE
cocos-creator写的APP调起sdk登录、签名、转账报错

### ISSUE THREAD

**Issue by dappbird** [TP-Lab/tp-js-sdk#25]
![833535723871428408](https://user-images.githubusercontent.com/59786369/158122787-7a3b01bc-4680-4bc3-b2f7-fd15e20ebca5.jpg)
![174780981298227984](https://user-images.githubusercontent.com/59786369/158122793-d0abb56a-4e76-4e96-b430-2b88fd0c3fa6.jpg)

https://user-images.githubusercontent.com/59786369/158122802-10741d5b-a603-460e-aaf4-090b3545843a.mp4

**Comment by NullPointerDuke** [comment]
贴一下调用参数

**Comment by dappbird** [comment]
![182027651389320018](https://user-images.githubusercontent.com/59786369/158771339-d0ce994f-e697-42e7-9931-d9c0eac971e2.png)
![65603691093190834](https://user-images.githubusercontent.com/59786369/158771348-3012a52b-7092-4f56-9dc2-ec904daf1511.png)
![602417567978546612](https://user-images.githubusercontent.com/59786369/158771357-74921ee1-e7ee-4597-b8ff-a219b3abae08.png)
![526538765289956544](https://user-images.githubusercontent.com/59786369/158771361-344fa164-ac9a-4e10-881f-9ab4d4242774.png)

**Comment by NullPointerDuke** [comment]
现在是钱包操作完成后，无法回调给App？请确认是否是在UI线程调用SDK的相关方法

**Comment by dappbird** [comment]
是的，在TP的UI调用的
