### ISSUE TITLE
 开发了一个简单的合约应用在 metamask 测试可以拉起 TP 失败

### ISSUE THREAD

**Issue by crapthings** [TP-Lab/tp-js-sdk#26]
用vConsole看不出什么原因啊

 开发了一个简单的合约应用在 metamask 测试可以拉起 TP 失败

这通常是什么情况啊？

ethers.js

**Comment by chendatony31** [comment]
当前账号是 ETH 相关的链么？ 可以试试这个 demo：  https://github.com/MetaMask/test-dapp 看下他的代码

**Comment by crapthings** [comment]
是的，现在合约部署在 rinkeby 测试链

snowpack 打包
ethers.js web3客户端

![image](https://user-images.githubusercontent.com/1147704/160807512-d8a301f9-e45c-4a77-822b-20af73ba3546.png)

执行合约方法就出这个什么 fetch 失败之类的

**Comment by chendatony31** [comment]
看下 network tab 那块 是不是节点报错了，节点需要允许 跨域， 方便的话可以也把 测试链接发来看下

**Comment by crapthings** [comment]
感谢 @chendatony31 有可能是网络问题，我再次确认部署到 rinkeby 钱包切换正确的网络，测试确实没问题

原来是我本地开发链和服务器部署的链都是 1337，网络被覆盖了，当chainId一样时，tp 会提示该网络已经存在，但是会把当前表单里的地址覆盖到已存的网络里
