### ISSUE TITLE
tp钱包移动端 对 eth_chainId 方法的支持存在问题，无法获取正确的链id

### ISSUE THREAD

**Issue by scz2011** [TP-Lab/tp-js-sdk#27]
1.在tp钱包添加rinkeby的测试网络，链 ID为4.
2.通过tp扫描 walletconnect 的二维码进行链接，链接时选择 在rinkeby网络中创建的账户。
3.钱包链接成功，使用  eth_chainId 方法获取链ID，显示 获取到的ID 为1.
多次测试均为此结果。
使用metamask，mathwallet对比测试。均可以获取正确的链 ID为4.

使用 dfox 也不存在此问题。

**Comment by scz2011** [comment]
更新 
1.  不是eth_chainId方法支持的问题，是使用 rinkeby的测试网络账户登录的时候，仍然进入到了主网络导致的此问题。
就是用tp钱包无法使用测试网络进行测试

**Comment by chendatony31** [comment]
创建 walletconnect 二维码的时候 要设置一个 chainid 来表明 需要哪个链的账号

**Comment by chendatony31** [comment]
https://github.com/WalletConnect/walletconnect-docs/blob/main/docs/quick-start/dapps/ethereum-provider.md

**Comment by cstommy** [comment]
谢谢，已经解决了
