### ISSUE TITLE
js sdk 没有支持币安的USDT转账吗？

### ISSUE THREAD

**Issue by cnzhang2022** [TP-Lab/tp-js-sdk#28]
js sdk 没有支持币安的USDT转账吗？ 找不到对应的转账接口

**Comment by chendatony31** [comment]
https://github.com/metamask/test-dapp  可以看这个 demo

**Comment by cnzhang2022** [comment]
只能转币安币 没有看到USDT

> https://github.com/metamask/test-dapp 可以看这个 demo

**Comment by chendatony31** [comment]
不可能每个币 都有啊 看 `transferTokens` 调合约

**Comment by cnzhang2022** [comment]
> 不可能每个币 都有啊 看 `transferTokens` 调合约

我是想用币安的USDT转账 不知道用那个接口
