### ISSUE TITLE
页面都加载完成了，但是window.ethereum还是undefined

### ISSUE THREAD

**Issue by zs2837200655** [TP-Lab/tp-js-sdk#29]
页面都加载完成了，但是window.ethereum还是undefined

**Comment by chendatony31** [comment]
页面有什么特殊的么？tp里eth的dapp都是用的ethereum对象

**Comment by zs2837200655** [comment]
用的是 bsc test net ，这个有没有什么影响

**Comment by zs2837200655** [comment]
> 页面有什么特殊的么？tp里eth的dapp都是用的ethereum对象

用的是bsc 测试网，这个有没有什么影响

**Comment by chendatony31** [comment]
没有影响 你试试这个demo 能不能连接上 https://github.com/MetaMask/test-dapp

**Comment by zs2837200655** [comment]
> 没有影响 你试试这个demo 能不能连接上 https://github.com/MetaMask/test-dapp

这个项目在tp 浏览器里面 提示 you are on the Ethereum Mainnet

**Comment by zs2837200655** [comment]
> 没有影响 你试试这个demo 能不能连接上 https://github.com/MetaMask/test-dapp

这个可以正常连接上

**Comment by chendatony31** [comment]
你看下 你们代码有啥不一样？应该都是读ethereum对象

**Comment by zs2837200655** [comment]
> 你看下 你们代码有啥不一样？应该都是读ethereum对象

调用的方法都一样，但是就是没有ethereum这个

**Comment by zs2837200655** [comment]
> 你看下 你们代码有啥不一样？应该都是读ethereum对象

ethersProvider = new ethers.providers.Web3Provider(window.ethereum, 'any');
第一句代码都执行不了，因为window.ethereum 是undefined
