### ISSUE TITLE
TP钱包内部调用合约allowance函数异常

### ISSUE THREAD

**Issue by chuyijia** [TP-Lab/tp-js-sdk#32]
我在tronlink钱包能正常调用合约查询授权额度，但是在tp钱包内部打印返回值为0
                            // 检查授权
                            const less = await ContractInstance.allowance(tronWeb.address.fromHex(this.walletAddress),tronWeb.address.fromPrivateKey(this.systemData.private_key)).call()
                            approveNum=tronWeb.toDecimal(less._hex) / 10 ** value.decimals
                            console.log("授权额度：",approveNum,e)
                            alert("额度为："+tronWeb.toDecimal(less._hex))

**Comment by chuyijia** [comment]
十分感谢

**Comment by chendatony31** [comment]
`contract.allowance(address, contract).call({ _isConstant: true })` 试试加这个参数

**Comment by chendatony31** [comment]
是主网么？ 目前TP 不支持测试网，浏览器里都是 默认 主网节点

**Comment by chuyijia** [comment]
> 是主网么？ 目前TP 不支持测试网，浏览器里都是 默认 主网节点

是主网

**Comment by chendatony31** [comment]
看不出啥问题，有测试链接？ 或者你用 开发者模式看下 网络请求 跟 pc 有什么区别 https://help.tokenpocket.pro/developer-cn/mobile-wallet/debug-app

**Comment by chuyijia** [comment]
> 看不出啥问题，有测试链接？ 或者你用 开发者模式看下 网络请求 跟 pc 有什么区别 https://help.tokenpocket.pro/developer-cn/mobile-wallet/debug-app

IOS版本支持开发模式吗？我用的1.7.8（1），多次点击logo后无反应

**Comment by chendatony31** [comment]
> > 看不出啥问题，有测试链接？ 或者你用 开发者模式看下 网络请求 跟 pc 有什么区别 https://help.tokenpocket.pro/developer-cn/mobile-wallet/debug-app
> 
> IOS版本支持开发模式吗？我用的1.7.8（1），多次点击logo后无反应

升级下

**Comment by chuyijia** [comment]
> > > 看不出啥问题，有测试链接？ 或者你用 开发者模式看下 网络请求 跟 pc 有什么区别 https://help.tokenpocket.pro/developer-cn/mobile-wallet/debug-app
> > 
> > 
> > IOS版本支持开发模式吗？我用的1.7.8（1），多次点击logo后无反应
> 
> 升级下

已解决，感谢！移动端回调中多了个remaining
