### ISSUE TITLE
Android app doesn't expose window.ethereum

### ISSUE THREAD

**Issue by jurosh** [TP-Lab/tp-js-sdk#33]
Hello,

your documentation for TokenPocket (https://help.tokenpocket.pro/developer-en/wallet/js-sdk) says:

"If your DApp already supports extension wallet protocols such as MetaMask, TronLink, Phantom, Scatter and iWallet, you can run it directly in the DApp browser of TokenPocket without any modification."

So I suppose that TokenPocket (mobile & dekstop) should always inject `window.ethereum` provider same way as Metamask ?

Because in Android app (in TokenPocket DApp browser) it looks like `window.ethereum` is not available and so I cannot unlock wallet in our dApp.

**Comment by jurosh** [comment]
I was able to narrow down this problem to CSP (Content Security Configuration) which seems to block injecting loading window.ethereum.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

There was same problem with MetaMask earlier, but they already fixed that in current versions. There still seems to be existing bug when using CSP in response header but in <meta /> it already works fine, https://github.com/MetaMask/metamask-extension/issues/3133.

So I suppose it should be possible to apply same fix also for TokenPocket to work with CSP in <meta /> tags.

**Comment by chendatony31** [comment]
Do you have a demo that works fine with metamask but not with TokenPocket? About the CSP, I don't we can solve this, as the CSP itself is to avoid injections. Maybe you can change your CSP rules?

**Comment by jurosh** [comment]
@chendatony31 I don't think this is anything what can be fixed in DApp itself. Added simple example hosted here https://jurosh.com/tokenpocket.html

HTML:
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- This is important -->
  <meta http-equiv="Content-Security-Policy" content="default-src 'self'">

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CSP Wallet Test</title>
  <script src="./tokenpocket.js"></script>
</head>
<body>
  <div id="app-target">
    Please wait...
  </div>
</body>
</html>
```

JavaScript:
```JavaScript
setTimeout(() => {
  const available = window.ethereum ? 'YES' : 'NO';
  const availableWallets = Object.keys(window.ethereum || {})
    .filter(key => key.startsWith('is'))
    .map(key => `<p>${key}</p>`);
  document.getElementById('app-target').innerHTML = `
    <p>Available: ${available}</p>
    <p>Wallets:</p>
    ${availableWallets}
  `
}, 2000)
```

Above code should display `YES` when `ethereum` is available. It works in all other mobile wallets except TokenPocket so there must be way how to inject. Maybe if TokenPocket would inject script above html CSP tag, it would work.

**Comment by jurosh** [comment]
Actually this seems to be related https://github.com/MetaMask/metamask-extension/pull/5693

**Comment by chendatony31** [comment]
OK, we will check it, and try find out a solution ASAP

**Comment by jurosh** [comment]
@chendatony31 anything new on this issue ?

**Comment by chendatony31** [comment]
@jurosh  It will be fixed in the coming release maybe on next week's Wednesday.

**Comment by chendatony31** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [celer bridger 支持, 跳转transit浏览器，修改Android注入方式](https://trello.com/c/ho87gBLr/8-celer-bridger-%E6%94%AF%E6%8C%81-%E8%B7%B3%E8%BD%ACtransit%E6%B5%8F%E8%A7%88%E5%99%A8%EF%BC%8C%E4%BF%AE%E6%94%B9android%E6%B3%A8%E5%85%A5%E6%96%B9%E5%BC%8F)
