### ISSUE TITLE
sdk里的一些方法在安卓用不了

### ISSUE THREAD

**Issue by hzx466494946** [TP-Lab/tp-js-sdk#34]
我需要唤醒分享功能，在苹果手机正常，但是在安卓手机上做不到！还有全屏api都用不了，希望能修复下

**Comment by hzx466494946** [comment]
vue版本2.5.2 tp-sdk-js版本3.7.4

`
<template>
    <button>分享</button>
    <button>全屏</button>
</template>
import tp from 'tp-js-sdk';
export default {
    data(){
        return {}
   }

}
`

**Comment by Developmc** [comment]
钱包版本升级到1.5.3以上了没
