### ISSUE TITLE
如何获取公钥

### ISSUE THREAD

**Issue by peter-jim** [TP-Lab/tp-js-sdk#38]
我们希望实现获取账户公钥，但是mobile端不支持，有能支持的库吗？

**Comment by chendatony31** [comment]
什么链的？ 拿公钥 做什么呢？

**Comment by chendatony31** [comment]
PC 端 是用的什么接口 或 库？

**Comment by peter-jim** [comment]
PC端用的是metamask 能正常获取到公钥，但是移动端官方文档指明暂不支持。在一些常用的钱包文档也没有找到相关方法
<img width="656" alt="image" src="https://user-images.githubusercontent.com/32545935/206915450-6fb977fb-581a-42dd-be4b-b8441861678c.png">

**Comment by chendatony31** [comment]
嗯 这个我们后面的版本会支持下
