### ISSUE TITLE
为什么我ios调用getCurrentWallet 观察钱包返回的walletType 也是normalWallet

### ISSUE THREAD

**Issue by 18810443670** [TP-Lab/tp-js-sdk#39]
我使用ios判断不了观察钱包 是为什么呢。 在bsc这条链上。

**Comment by justXyS** [comment]
现在返回是有点问题,下个版本修复

**Comment by 18810443670** [comment]
@justXyS  请问一下具体的上线时间节点有吗。 我这边方便及时修改。

**Comment by chendatony31** [comment]
已经修复了 @18810443670  但是不建议直接用这个，如果是需要验证用户是否真的持有 私钥，要求用户签名并验证是最常用的方式。 参考： https://help.tokenpocket.pro/developer-cn/extension-wallet/api-reference/signing-aata
