### ISSUE TITLE
如何实现二维码连接钱包

### ISSUE THREAD

**Issue by lifuzhao100** [TP-Lab/tp-js-sdk#47]
您好，我司在开发一个pc端网站，在网站中展示二维码，支持用户通过tokenpocket app扫二维码连接tokenpocket wallet，我在官方文档中没有找到相关的描述，想请问下，tokenpocket支持这种连接方式吗？

**Comment by Developmc** [comment]
1. TP目前的SDK支持**App内互相拉起-连接**，文档看这里：https://github.com/TP-Lab/Mobile-SDK/tree/master/Android%20SDK。
2.你的应用是PC端网站，展示二维码，比较适合用“WalletConnect”的方式连接(目前TP也支持)，文档见：https://specs.walletconnect.com/2.0

**Comment by lifuzhao100** [comment]
> 1.TP目前的SDK支持**App内互相拉起-连接**，文档看这里：[https://github.com/TP-Lab/Mobile-SDK/tree/master/Android%20SDK。](https://github.com/TP-Lab/Mobile-SDK/tree/master/Android%20SDK%E3%80%82) 2.你的应用是PC端网站，展示二维码，比较适合用“WalletConnect”的方式连接(目前TP也支持)，文档见：https://specs.walletconnect.com/2.0

谢谢！

**Comment by lifuzhao100** [comment]
done
