### ISSUE TITLE
invokeQRScanner

### ISSUE THREAD

**Issue by LeoTian888** [TP-Lab/tp-js-sdk#49]
测试tp.invokeQRScanner()
点击扫码后对二维码进行扫描功能正常
点击扫码然后点击取消，再点击扫码则无法使用扫码功能，除非重新加载网页。
  <button type="primary" @click="scanQR">扫描QR码</button>
  <h1>{{ qrResult }}</h1>

scanQR(){
      let that = this;
      tp.invokeQRScanner()
        .then(res => {
          that.qrResult = res;
        })
        .catch((error)=>{
          console.log(error);
        })
    }

**Comment by Developmc** [comment]
Android 端还是 iOS 端

**Comment by LeoTian888** [comment]
> Android 端还是 iOS 端

iOS 18.1.1，TP 2.5.4

**Comment by Developmc** [comment]
OK，方便提供一下测试链接不

**Comment by LeoTian888** [comment]
> OK，方便提供一下测试链接不

现在已经在服务器上删除了，用的vue3做的测试
测试用代码
main.js
`import { createApp } from 'vue'
import App from './App.vue'
import Varlet from '@varlet/ui'
import '@varlet/ui/es/style'

createApp(App).use(Varlet).mount('#app')
`
app.vue
`<template>
  <var-button type="primary" @click="scanQR">扫描QR码</var-button>
  <h1>{{ qrResult }}</h1>
</template>

<script>
import tp from "tp-js-sdk"
export default {
  name: 'App',

  data(){
    return{
      qrResult:"0000",
    }
  },
  methods:{
    scanQR(){
      let that = this;
      tp.invokeQRScanner()
        .then(res => {
          that.qrResult = res;
        })
        .catch((error)=>{
          console.log(error);
        })
    }
  }
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
`

**Comment by Developmc** [comment]
下个版本将会修复，感谢反馈
