### ISSUE TITLE
井通签名何时可以支持手续费?

### ISSUE THREAD

**Issue by yongjunfan0723** [TP-Lab/tp-js-sdk#5]

**Comment by chendatony31** [comment]
参数那里没有严格限制，理论上 直接添加 对应字段就可以了 @yongjunfan0723

**Comment by yongjunfan0723** [comment]
添加了Platform字段，但签名后res.msg 是 JSON contains unknown field: "Platform"

**Comment by chendatony31** [comment]
解决了么？  @yongjunfan0723
